Repository wbalmer/backtracks, pull requests merged in 2024-01, with the labels that each got.

#47 Explicitly set reference epoch, save chi2 to object, and fixes plotting for stationary tracks
  .gitignore
  backtracks/backtracks.py
  backtracks/plotting.py
  docs/tutorial.ipynb
  tests/test_backtracks.py
Labels: bug, enhancement

#50 Updated docstrings + bugfix pol2car
  backtracks/backtracks.py
  backtracks/plotting.py
  backtracks/utils.py
  docs/backtracks.rst
Labels: bug, documentation

#54 Slightly updated docs.
  backtracks/backtracks.py
  backtracks/utils.py
Labels: documentation

#55 Protect against maskedconstant return from gaia query of no RV
  backtracks/backtracks.py
Labels: bug
